<?php

/**
 * @file
 * Contains idix_multistep.module.
 */

use Drupal\Core\Form\FormStateInterface;

function idix_multistep_theme($existing, $type, $theme, $path) {
  return [
    'multistep_indicator' => [
      'template' => 'multistep/indicator',
      'variables' => [
        'steps' => [],
        'current_step' => 0,
      ]
    ]
  ];
}

function idix_multistep_preprocess_multistep_indicator(&$vars){
  $steps = $vars['steps'];
  $steps_to_show = [];
  foreach($steps as $step_number => $step){
    $format_settings = $step->format_settings;
    if ($format_settings['show_step_title']) {
      $steps_to_show[$step_number] = $step;
    }
  }
  $vars['raw_steps'] = $steps;
  $vars['steps'] = $steps_to_show;
}

/**
 * Implements hook_form_alter().
 */
function idix_multistep_form_alter(&$form, FormStateInterface &$form_state) {
  // Check if form using form group multi step field.
  /** @var \Drupal\idix_multistep\MultistepFactory $multistep_factory */
  $multistep_factory = \Drupal::service('multistep_factory');
  if ($multistep_factory->check_form_multistep($form)) {

    /** @var \Drupal\idix_multistep\MultistepController $multiStep */
    if ($multiStep = $form_state->get('multistep_controller')) {
      $multiStep->updateStepInfo();
    }
    else {
      $multiStep = $multistep_factory->getMultiStepController($form, $form_state);
    }

    $multiStep->rebuildForm($form);

    $form_state->set('multistep_controller', $multiStep);
  }
}